import { Inter } from "next/font/google";
import "./globals.css";
import MenuComp from "./components/MenuComp";
import {Layout} from 'antd';
import { UserProvider } from "./context/UserContext";
const { Header, Content, Footer, Sider } = Layout;
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <UserProvider>
      <html lang="en">
        <body className={inter.className} style={{minHeight: "100vh"}}>
        <MenuComp>
          {children}
        </MenuComp>
        </body>
      </html>
    </UserProvider>
  );
}
